// src/frontend/dashboard-react/src/main.tsx
import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import { initializeStoredBrandVariant } from '@workout-lab/frontend-common/branding'
import { initializeStoredTheme } from '@workout-lab/frontend-common/theme'
import './index.css'
import App from './App.tsx'

initializeStoredBrandVariant()
initializeStoredTheme()

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <App />
  </StrictMode>,
)

// src/frontend/settings-solid/src/main.tsx
import { render } from 'solid-js/web'
import { initializeStoredBrandVariant } from '@workout-lab/frontend-common/branding'
import { initializeStoredTheme } from '@workout-lab/frontend-common/theme'
import App from './App'
import './style.css'

const root = document.getElementById('root')

if (root) {
  initializeStoredBrandVariant()
  initializeStoredTheme()
  render(() => <App />, root)
}
